<?php
/**
 * Auto-generated guard to ensure the justDev Support plugin remains mandatory.
 * Do not edit this file manually. It will be recreated if removed.
 */
if (function_exists('is_blog_installed') && !is_blog_installed()) {
	return;
}
if (!defined('JD_SUPPORT_VERSION')) {
	wp_die('This site requires the justDev Support plugin to run.');
}
