<?php
/**
 * Auto-generated guard to ensure the justDev Support plugin remains mandatory.
 * Do not edit this file manually. It will be recreated if removed.
 */
if (!defined('JD_SUPPORT_VERSION')) {
	wp_die('This site requires the justDev Support plugin to run.');
}
